### ISSUE TITLE
 Music-Duration-Reducer Fabric 1.1.3 crashes on opening config

### ISSUE THREAD

**Issue by UltimateBoomer** [LudoCrypt/Music-Duration-Reducer#1]
With version 1.1.3 installed, the game crashes when I open the config of any mod from mod menu. 1.1.2 works fine. I think something might be wrong with the auto config/cloth config setup.
[crash-2020-12-29_21.28.18-client.txt](https://github.com/LudoCrypt/Music-Duration-Reducer/files/5752837/crash-2020-12-29_21.28.18-client.txt)

**Comment by LudoCrypt** [comment]
Hm, I'm not sure what could be causing this. Maybe a conflict with optifabric or Slight GUI modifications. Works fine for me, so it has to be a mod conflict

**Comment by UltimateBoomer** [comment]
Sorry, turns out one of my mods was outdated and updating it fixed the problem.
