### ISSUE TITLE
GREAT MOD!! .. but plays ALL tunes despite installing the "Nikola219's New Ambient Music Remover" resource pack

### ISSUE THREAD

**Issue by markygnlg** [LudoCrypt/Music-Duration-Reducer#10]
I LOVE what your mod does & the way your mod is sooo customisable, but I do not like the newer music with it's harsh tones (the piano keys sound like they're being hit 'hard' as apposed to 'soft' - I played a few pianos when younger; harder hit keys are sharper) & faster pace too - so I installed "Nikola219's New Ambient Music Remover" resource pack.

I've found that your fantastic mod ignores those settings & I was hoping that I could find a way around it (I've tried setting up the order in my 'resourse packs list' but your mod does not show up there:

 - is there a way to setup your mod to work with the old music?
 - is there a way to setup your mod to work with resource packs?

If not, then not.

Thanks either way.

**Comment by LudoCrypt** [comment]
literally impossible
my mod cant do that. its an issue with the pack

**Comment by markygnlg** [comment]
Thanks for the fast reply!

It's all good now as the "[Infinite Music](https://www.curseforge.com/minecraft/mc-mods/infinite-music)" mod does exactly what I want

Thanks again.
