### ISSUE TITLE
Game Crashed, "NullPointerException"

### ISSUE THREAD

**Issue by MythrilBagels** [LudoCrypt/Music-Duration-Reducer#6]
`The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.ForgeConfigSpec$BooleanValue.get()" because "net.ludocrypt.musicdr.config.MusicConfig.divide" is null`
What I've gathered from this crash is the game is reading the config file wrong, as it says the value for "divide" is null, despite the fact it has the default number in it as I haven't changed it.

**Comment by Stormalisk** [comment]
I am getting this too, but for me, it seems to be something when I install a mod that needs a different forge version.

Instead of getting the error screen from that mod, stating that I need a forge update, it just crashes with the null report.

**Comment by CaptainAhmed18** [comment]
I Also got that. Needs Urgent Fix.

**Comment by HalestormXV** [comment]
I can also state that this issue is indeed occurring on the Forge version. Specifically Forge version **39.0.64**
