### ISSUE TITLE
[1.19.2 / FORGE] Do not launch with mod installed.

### ISSUE THREAD

**Issue by murao-kun** [LudoCrypt/Music-Duration-Reducer#9]
The title explains everything.

**Comment by LudoCrypt** [comment]
The title explains nothing

**Comment by murao-kun** [comment]
When I install mod on 1.19.1 forge my instance crashing on startup without the report.
There is logs:
[debug.log](https://github.com/LudoCrypt/Music-Duration-Reducer/files/9259278/debug.log)
[latest.log](https://github.com/LudoCrypt/Music-Duration-Reducer/files/9259279/latest.log)

**Comment by murao-kun** [comment]
Is it enough?

**Comment by murao-kun** [comment]
New 3.0.0 version still doing the same.
[debug.log](https://github.com/LudoCrypt/Music-Duration-Reducer/files/9776720/debug.log)
[latest.log](https://github.com/LudoCrypt/Music-Duration-Reducer/files/9776721/latest.log)

**Comment by LudoCrypt** [comment]
Fixed in 3.0.0-hotfix
